### ISSUE TITLE
可以上传一下数据库表结构吗？

### ISSUE THREAD

**Issue by LeolichN** [stringl1l1l1l/MovieHunter#4]

**Comment by stringl1l1l1l** [comment]
可以，稍等。




南航&nbsp;陈立文
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stringl1l1l1l/MovieHunter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月19日(星期一) 下午2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[stringl1l1l1l/MovieHunter] 可以上传一下数据库表结构吗？ (Issue #4)

**Comment by stringl1l1l1l** [comment]
我已经提交数据库脚本到github仓库里了，如果你需要具体的数据（数据量较大），我可以作为附件发给你。


南航&nbsp;陈立文
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stringl1l1l1l/MovieHunter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月19日(星期一) 下午2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[stringl1l1l1l/MovieHunter] 可以上传一下数据库表结构吗？ (Issue #4)

**Comment by LeolichN** [comment]
> 我已经提交数据库脚本到github仓库里了，如果你需要具体的数据（数据量较大），我可以作为附件发给你。 南航&nbsp;陈立文 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "stringl1l1l1l/MovieHunter" ***@***.***&gt;; 发送时间:&nbsp;2024年2月19日(星期一) 下午2:49 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[stringl1l1l1l/MovieHunter] 可以上传一下数据库表结构吗？ (Issue #4) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

可以了，非常感谢
